schemaVersion: 1.0.0
commandTests:
- name: "node"
  command: ["node", "--version"]
  expectedOutput: ["v18.20.8"]
- name: "python"
  command: ["python3", "--version"]
  expectedOutput: ["Python 3.13.13"]
